---
language: python
python: 3.6

sudo: required
services:
  - docker

env:
  - CONTEXT=.
  - CONTEXT=1.3.0
  - CONTEXT=1.2.0
  - CONTEXT=1.1.0
  - CONTEXT=1.0.0
  - CONTEXT=0.10.0
  - CONTEXT=0.9.0

script:
  - docker build $CONTEXT

stages:
  - lint python code
  - verify update was run
  - test

jobs:
  include:
    - stage: lint python code
      install: pip install tox
      script: tox

    - stage: verify update was run
      script:
        - ./update.py
        - test -z "$(git status -s)"
